version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sms_campaign
      MYSQL_USER: adn
      MYSQL_PASSWORD: adn@1234
      MYSQL_ROOT_PASSWORD: adn@1234
    volumes:
      - ./../mysql:/var/lib/mysql